# Generated by Django 4.2.13 on 2026-06-08 04:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ordenes', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FacturaInterna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_factura', models.CharField(help_text='Generado automáticamente: FAC-YYYYMMDD-NNNN', max_length=20, unique=True, verbose_name='N° Factura')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EMITIDA', 'Emitida'), ('ANULADA', 'Anulada')], default='PENDIENTE', max_length=15, verbose_name='Estado')),
                ('subtotal_mano_obra', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Subtotal mano de obra ($)')),
                ('subtotal_repuestos', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Subtotal repuestos ($)')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Subtotal ($)')),
                ('iva', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='IVA 15% ($)')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total ($)')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('fecha_emision', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de emisión')),
                ('fecha_anulacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de anulación')),
                ('emitido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas_emitidas', to=settings.AUTH_USER_MODEL, verbose_name='Emitido por')),
                ('orden', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='factura', to='ordenes.ordenservicio', verbose_name='Orden de servicio')),
            ],
            options={
                'verbose_name': 'Factura interna',
                'verbose_name_plural': 'Facturas internas',
                'ordering': ['-fecha_emision'],
                'indexes': [models.Index(fields=['numero_factura'], name='facturacion_numero__441721_idx'), models.Index(fields=['orden'], name='facturacion_orden_i_11b673_idx'), models.Index(fields=['estado'], name='facturacion_estado_47bf9c_idx'), models.Index(fields=['fecha_emision'], name='facturacion_fecha_e_ff71c7_idx')],
            },
        ),
    ]
