# Generated by Django 4.2.13 on 2026-06-28 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturainterna',
            name='fecha_anulacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de anulacion'),
        ),
        migrations.AlterField(
            model_name='facturainterna',
            name='fecha_emision',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de emision'),
        ),
        migrations.AlterField(
            model_name='facturainterna',
            name='numero_factura',
            field=models.CharField(help_text='Generado automaticamente: FAC-YYYYMMDD-NNNN', max_length=20, unique=True, verbose_name='N Factura'),
        ),
    ]
