# Generated by Django 4.2.13 on 2026-06-28 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0002_alter_facturainterna_fecha_anulacion_and_more'),
        ('ordenes', '0004_detalleordentrabajo_ordentrabajo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturainterna',
            name='orden',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='factura', to='ordenes.ordentrabajo', verbose_name='Orden de trabajo'),
        ),
    ]
