# Generated by Django 4.2.13 on 2026-05-18 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('SERVICIO', 'Servicio / Mano de obra'), ('REPUESTO', 'Repuesto / Material')], default='SERVICIO', max_length=10, verbose_name='Tipo')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripción')),
                ('cantidad', models.DecimalField(decimal_places=2, default=1, max_digits=8, verbose_name='Cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio unitario ($)')),
            ],
            options={
                'verbose_name': 'Detalle de orden',
                'verbose_name_plural': 'Detalles de orden',
            },
        ),
        migrations.CreateModel(
            name='EvidenciaOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='evidencias/', verbose_name='Imagen')),
                ('descripcion', models.CharField(blank=True, max_length=200, verbose_name='Descripción')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de subida')),
            ],
            options={
                'verbose_name': 'Evidencia',
                'verbose_name_plural': 'Evidencias',
            },
        ),
        migrations.CreateModel(
            name='OrdenServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_orden', models.CharField(help_text='Generado automáticamente: OS-YYYYMMDD-NNNN', max_length=20, unique=True, verbose_name='N° Orden')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En proceso'), ('FINALIZADO', 'Finalizado'), ('ENTREGADO', 'Entregado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=15, verbose_name='Estado')),
                ('prioridad', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente')], default='MEDIA', max_length=10, verbose_name='Prioridad')),
                ('kilometraje_ingreso', models.PositiveIntegerField(default=0, verbose_name='Kilometraje al ingreso')),
                ('descripcion_problema', models.TextField(verbose_name='Descripción del problema')),
                ('diagnostico', models.TextField(blank=True, verbose_name='Diagnóstico técnico')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de ingreso')),
                ('fecha_estimada_entrega', models.DateField(blank=True, null=True, verbose_name='Fecha estimada de entrega')),
                ('fecha_entrega_real', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de entrega real')),
                ('costo_mano_obra', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Costo mano de obra ($)')),
                ('costo_repuestos', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Costo repuestos ($)')),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Descuento ($)')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes', to='clientes.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Orden de servicio',
                'verbose_name_plural': 'Órdenes de servicio',
                'ordering': ['-fecha_ingreso'],
            },
        ),
    ]
