# Generated by Django 4.2.13 on 2026-05-18 01:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehiculos', '0001_initial'),
        ('ordenes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenservicio',
            name='recepcionista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_recibidas', to=settings.AUTH_USER_MODEL, verbose_name='Recepcionista'),
        ),
        migrations.AddField(
            model_name='ordenservicio',
            name='tecnico_asignado',
            field=models.ForeignKey(blank=True, limit_choices_to={'rol': 'MECANICO'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_asignadas', to=settings.AUTH_USER_MODEL, verbose_name='Técnico asignado'),
        ),
        migrations.AddField(
            model_name='ordenservicio',
            name='vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes', to='vehiculos.vehiculo', verbose_name='Vehículo'),
        ),
        migrations.AddField(
            model_name='evidenciaorden',
            name='orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='ordenes.ordenservicio', verbose_name='Orden'),
        ),
        migrations.AddField(
            model_name='detalleorden',
            name='orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ordenes.ordenservicio', verbose_name='Orden'),
        ),
        migrations.AddIndex(
            model_name='ordenservicio',
            index=models.Index(fields=['numero_orden'], name='ordenes_ord_numero__b00270_idx'),
        ),
        migrations.AddIndex(
            model_name='ordenservicio',
            index=models.Index(fields=['estado'], name='ordenes_ord_estado_4a5708_idx'),
        ),
        migrations.AddIndex(
            model_name='ordenservicio',
            index=models.Index(fields=['vehiculo'], name='ordenes_ord_vehicul_f9b5e6_idx'),
        ),
        migrations.AddIndex(
            model_name='ordenservicio',
            index=models.Index(fields=['cliente'], name='ordenes_ord_cliente_5d5fa4_idx'),
        ),
        migrations.AddIndex(
            model_name='ordenservicio',
            index=models.Index(fields=['fecha_ingreso'], name='ordenes_ord_fecha_i_829493_idx'),
        ),
    ]
