# Generated by Django 4.2.13 on 2026-06-28 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0003_servicio_precio_remove_evidencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleOrdenTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('SERVICIO', 'Servicio / Mano de obra'), ('REPUESTO', 'Repuesto / Material')], default='SERVICIO', max_length=10, verbose_name='Tipo')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripcion')),
                ('cantidad', models.DecimalField(decimal_places=2, default=1, max_digits=8, verbose_name='Cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio unitario ($)')),
            ],
            options={
                'verbose_name': 'Detalle de orden de trabajo',
                'verbose_name_plural': 'Detalles de orden de trabajo',
            },
        ),
        migrations.CreateModel(
            name='OrdenTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_orden', models.CharField(help_text='Generado automaticamente: OT-YYYYMMDD NNNN', max_length=20, unique=True, verbose_name='N Orden')),
                ('estado', models.CharField(choices=[('RECIBIDA', 'Recibida'), ('DIAGNOSTICO', 'Diagnostico'), ('COTIZADA', 'Cotizada'), ('APROBADA', 'Aprobada'), ('EN_PROCESO', 'En proceso'), ('ESPERANDO_REPUESTOS', 'Esperando repuestos'), ('FINALIZADA', 'Finalizada'), ('ENTREGADA', 'Entregada'), ('CANCELADA', 'Cancelada')], default='RECIBIDA', max_length=25, verbose_name='Estado')),
                ('prioridad', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente')], default='MEDIA', max_length=10, verbose_name='Prioridad')),
                ('tipo_trabajo', models.CharField(choices=[('MANTENIMIENTO_PREVENTIVO', 'Mantenimiento Preventivo'), ('MECANICA_GENERAL', 'Mecanica General'), ('COLISION_ENDEREZADA', 'Colision y Enderezada'), ('PINTURA', 'Pintura'), ('DIAGNOSTICO', 'Diagnostico')], default='MECANICA_GENERAL', max_length=30, verbose_name='Tipo de trabajo')),
                ('kilometraje_ingreso', models.PositiveIntegerField(default=0, verbose_name='Kilometraje al ingreso')),
                ('descripcion_problema', models.TextField(verbose_name='Descripcion del problema')),
                ('diagnostico', models.TextField(blank=True, verbose_name='Diagnostico tecnico')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de ingreso')),
                ('fecha_estimada_entrega', models.DateField(blank=True, null=True, verbose_name='Fecha estimada de entrega')),
                ('fecha_entrega_real', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de entrega real')),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio del servicio ($)')),
                ('costo_mano_obra', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Costo mano de obra ($)')),
                ('costo_repuestos', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Costo repuestos ($)')),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Descuento ($)')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Orden de trabajo',
                'verbose_name_plural': 'Ordenes de trabajo',
                'ordering': ['-fecha_ingreso'],
            },
        ),
        migrations.RemoveField(
            model_name='ordenservicio',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='ordenservicio',
            name='recepcionista',
        ),
        migrations.RemoveField(
            model_name='ordenservicio',
            name='servicio',
        ),
        migrations.RemoveField(
            model_name='ordenservicio',
            name='tecnico_asignado',
        ),
        migrations.RemoveField(
            model_name='ordenservicio',
            name='vehiculo',
        ),
        migrations.DeleteModel(
            name='DetalleOrden',
        ),
    ]
