# Generated by Django 4.2.13 on 2026-06-28 18:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cotizaciones', '0004_alter_cotizacion_orden_generada_and_more'),
        ('mantenimiento', '0005_alter_historialmantenimiento_orden_and_more'),
        ('alertas', '0005_alter_alerta_orden_alter_alerta_tipo_and_more'),
        ('clientes', '0002_remove_cliente_telefono_alternativo'),
        ('ordenes', '0004_detalleordentrabajo_ordentrabajo_and_more'),
        ('inventario', '0003_movimientoinventario_orden_trabajo_and_more'),
        ('vehiculos', '0002_remove_vehiculo_foto_restringir_tipos'),
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrdenServicio',
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_trabajo', to='clientes.cliente', verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='recepcionista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_trabajo_recibidas', to=settings.AUTH_USER_MODEL, verbose_name='Recepcionista'),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_trabajo', to='servicios.servicio', verbose_name='Servicio'),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='tecnico_asignado',
            field=models.ForeignKey(blank=True, limit_choices_to={'rol': 'MECANICO'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_trabajo_asignadas', to=settings.AUTH_USER_MODEL, verbose_name='Tecnico asignado'),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_trabajo', to='vehiculos.vehiculo', verbose_name='Vehiculo'),
        ),
        migrations.AddField(
            model_name='detalleordentrabajo',
            name='orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ordenes.ordentrabajo', verbose_name='Orden de trabajo'),
        ),
        migrations.AddIndex(
            model_name='ordentrabajo',
            index=models.Index(fields=['numero_orden'], name='ordenes_ord_numero__e0412a_idx'),
        ),
        migrations.AddIndex(
            model_name='ordentrabajo',
            index=models.Index(fields=['estado'], name='ordenes_ord_estado_89e5f9_idx'),
        ),
        migrations.AddIndex(
            model_name='ordentrabajo',
            index=models.Index(fields=['vehiculo'], name='ordenes_ord_vehicul_3846d1_idx'),
        ),
        migrations.AddIndex(
            model_name='ordentrabajo',
            index=models.Index(fields=['cliente'], name='ordenes_ord_cliente_67c6a4_idx'),
        ),
        migrations.AddIndex(
            model_name='ordentrabajo',
            index=models.Index(fields=['fecha_ingreso'], name='ordenes_ord_fecha_i_3de37d_idx'),
        ),
    ]
