# Generated by Django 4.2.13 on 2026-06-28 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_alter_servicio_options_servicio_categoria_and_more'),
        ('ordenes', '0005_delete_ordenservicio_ordentrabajo_cliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleordentrabajo',
            name='servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='detalles_ordenes', to='servicios.servicio', verbose_name='Servicio del catalogo'),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='autorizacion_cliente',
            field=models.TextField(blank=True, verbose_name='Autorizacion del cliente'),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='descripcion_problema',
            field=models.TextField(verbose_name='Sintomas reportados por el cliente'),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='numero_orden',
            field=models.CharField(help_text='Generado automaticamente: OT-YYYYMMDD-NNNN', max_length=20, unique=True, verbose_name='N Orden'),
        ),
    ]
