# Generated by Django 4.2.13 on 2026-07-06 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_movimientoinventario_orden_trabajo_and_more'),
        ('ordenes', '0006_detalleordentrabajo_servicio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleordentrabajo',
            name='repuesto_inventario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detalles_ordenes', to='inventario.repuesto', verbose_name='Repuesto del inventario'),
        ),
    ]
