# Generated by Django 4.2.13 on 2026-07-15 04:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ordenes', '0007_detalleordentrabajo_repuesto_inventario'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordentrabajo',
            name='canal_recordatorio',
            field=models.CharField(choices=[('EMAIL', 'Correo electronico'), ('WHATSAPP', 'WhatsApp'), ('AMBOS', 'Correo y WhatsApp')], default='EMAIL', max_length=10, verbose_name='Canal de envio del recordatorio'),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='intervalo_dias_recordatorio',
            field=models.PositiveIntegerField(blank=True, help_text='Ej: 90 = cada 3 meses. Dejar en blanco si no aplica.', null=True, verbose_name='Intervalo en dias para el proximo mantenimiento'),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='intervalo_km_recordatorio',
            field=models.PositiveIntegerField(blank=True, help_text='Ej: 5000. Dejar en blanco si no aplica.', null=True, verbose_name='Intervalo en km para el proximo mantenimiento'),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='requiere_recordatorio',
            field=models.BooleanField(default=False, help_text='Activar para programar un recordatorio automatico al cliente.', verbose_name='Requiere recordatorio de mantenimiento'),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='tecnico_asignado',
            field=models.ForeignKey(blank=True, limit_choices_to={'rol__codigo': 'MECANICO'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_trabajo_asignadas', to=settings.AUTH_USER_MODEL, verbose_name='Tecnico asignado'),
        ),
    ]
