# Generated by Django 4.2.13 on 2026-07-15 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0009_autorizacion_cliente_boolean'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordentrabajo',
            name='aplica_iva',
            field=models.BooleanField(default=False, verbose_name='Aplica IVA'),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='porcentaje_iva',
            field=models.PositiveSmallIntegerField(default=15, verbose_name='Porcentaje IVA (%)'),
        ),
    ]
