# Generated by Django 4.2.13 on 2026-06-28 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cotizacion',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Cotizacion', 'verbose_name_plural': 'Cotizaciones'},
        ),
        migrations.AlterModelOptions(
            name='detallecotizacion',
            options={'verbose_name': 'Detalle de cotizacion', 'verbose_name_plural': 'Detalles de cotizacion'},
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='descripcion',
            field=models.TextField(blank=True, verbose_name='Descripcion del trabajo'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='fecha_aprobacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de aprobacion'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='fecha_validez',
            field=models.DateField(blank=True, null=True, verbose_name='Valida hasta'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='numero_cotizacion',
            field=models.CharField(max_length=20, unique=True, verbose_name='N Cotizacion'),
        ),
    ]
