# Generated by Django 4.2.13 on 2026-06-28 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0003_alter_cotizacion_options_and_more'),
        ('vehiculos', '0002_remove_vehiculo_foto_restringir_tipos'),
        ('ordenes', '0004_detalleordentrabajo_ordentrabajo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='orden_generada',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizacion_origen', to='ordenes.ordentrabajo', verbose_name='Orden de trabajo generada'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cotizaciones', to='vehiculos.vehiculo', verbose_name='Vehiculo'),
        ),
        migrations.AlterField(
            model_name='detallecotizacion',
            name='cotizacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='cotizaciones.cotizacion', verbose_name='Cotizacion'),
        ),
        migrations.AlterField(
            model_name='detallecotizacion',
            name='descripcion',
            field=models.CharField(max_length=200, verbose_name='Descripcion'),
        ),
    ]
