# Generated by Django 4.2.13 on 2026-06-28 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0004_alter_cotizacion_orden_generada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='fecha_envio',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de envio'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('ENVIADA', 'Enviada'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada')], default='BORRADOR', max_length=15, verbose_name='Estado'),
        ),
    ]
