# Generated by Django 4.2.13 on 2026-06-28 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_alter_servicio_options_servicio_categoria_and_more'),
        ('cotizaciones', '0005_cotizacion_fecha_envio_alter_cotizacion_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='aplica_iva',
            field=models.BooleanField(default=False, verbose_name='Aplica IVA (15%)'),
        ),
        migrations.AddField(
            model_name='detallecotizacion',
            name='servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='detalles_cotizacion', to='servicios.servicio', verbose_name='Servicio del catalogo'),
        ),
    ]
