# Generated by Django 4.2.13 on 2026-05-18 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('CEDULA', 'Cédula'), ('RUC', 'RUC'), ('PASAPORTE', 'Pasaporte')], default='CEDULA', max_length=10, verbose_name='Tipo de documento')),
                ('numero_documento', models.CharField(max_length=20, unique=True, verbose_name='Número de documento')),
                ('nombres', models.CharField(max_length=100, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('telefono_alternativo', models.CharField(blank=True, max_length=20, verbose_name='Teléfono alternativo')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo electrónico')),
                ('direccion', models.TextField(blank=True, verbose_name='Dirección')),
                ('ciudad', models.CharField(default='Guayaquil', max_length=80, verbose_name='Ciudad')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['apellidos', 'nombres'],
                'indexes': [models.Index(fields=['numero_documento'], name='clientes_cl_numero__868cb7_idx'), models.Index(fields=['apellidos', 'nombres'], name='clientes_cl_apellid_ee7b54_idx')],
            },
        ),
    ]
