# Generated by Django 4.2.13 on 2026-06-08 04:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ordenes', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaRepuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Creada el')),
            ],
            options={
                'verbose_name': 'Categoría de repuesto',
                'verbose_name_plural': 'Categorías de repuestos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Repuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código único del repuesto', max_length=50, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('marca', models.CharField(blank=True, max_length=100, verbose_name='Marca')),
                ('modelo', models.CharField(blank=True, max_length=100, verbose_name='Modelo')),
                ('stock_actual', models.PositiveIntegerField(default=0, verbose_name='Stock actual')),
                ('stock_minimo', models.PositiveIntegerField(default=5, help_text='Alerta cuando el stock baje de este valor', verbose_name='Stock mínimo')),
                ('stock_maximo', models.PositiveIntegerField(blank=True, help_text='Stock máximo recomendado', null=True, verbose_name='Stock máximo')),
                ('precio_compra', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio de compra ($)')),
                ('precio_venta', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio de venta ($)')),
                ('ubicacion', models.CharField(blank=True, help_text='Ej: Estante A-3, Caja 2', max_length=100, verbose_name='Ubicación en bodega')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='repuestos', to='inventario.categoriarepuesto', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Repuesto',
                'verbose_name_plural': 'Repuestos',
                'ordering': ['categoria', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida'), ('AJUSTE', 'Ajuste'), ('DEVOLUCION', 'Devolución')], max_length=15, verbose_name='Tipo de movimiento')),
                ('cantidad', models.IntegerField(help_text='Positivo para entrada, negativo para salida', verbose_name='Cantidad')),
                ('stock_anterior', models.PositiveIntegerField(verbose_name='Stock anterior')),
                ('stock_nuevo', models.PositiveIntegerField(verbose_name='Stock nuevo')),
                ('motivo', models.TextField(blank=True, verbose_name='Motivo')),
                ('fecha_movimiento', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del movimiento')),
                ('orden_servicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_inventario', to='ordenes.ordenservicio', verbose_name='Orden de servicio')),
                ('realizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_realizados', to=settings.AUTH_USER_MODEL, verbose_name='Realizado por')),
                ('repuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='inventario.repuesto', verbose_name='Repuesto')),
            ],
            options={
                'verbose_name': 'Movimiento de inventario',
                'verbose_name_plural': 'Movimientos de inventario',
                'ordering': ['-fecha_movimiento'],
            },
        ),
        migrations.AddIndex(
            model_name='repuesto',
            index=models.Index(fields=['codigo'], name='inventario__codigo_74f284_idx'),
        ),
        migrations.AddIndex(
            model_name='repuesto',
            index=models.Index(fields=['categoria'], name='inventario__categor_4bdbe4_idx'),
        ),
        migrations.AddIndex(
            model_name='repuesto',
            index=models.Index(fields=['activo'], name='inventario__activo_87df55_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientoinventario',
            index=models.Index(fields=['repuesto'], name='inventario__repuest_45d908_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientoinventario',
            index=models.Index(fields=['tipo'], name='inventario__tipo_b85d84_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientoinventario',
            index=models.Index(fields=['fecha_movimiento'], name='inventario__fecha_m_ff429d_idx'),
        ),
    ]
