# Generated by Django 4.2.13 on 2026-06-28 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriarepuesto',
            options={'ordering': ['nombre'], 'verbose_name': 'Categoria de repuesto', 'verbose_name_plural': 'Categorias de repuestos'},
        ),
        migrations.RemoveField(
            model_name='movimientoinventario',
            name='orden_servicio',
        ),
    ]
