# Generated by Django 4.2.13 on 2026-06-28 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_alter_categoriarepuesto_options_and_more'),
        ('ordenes', '0004_detalleordentrabajo_ordentrabajo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientoinventario',
            name='orden_trabajo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_inventario', to='ordenes.ordentrabajo', verbose_name='Orden de trabajo'),
        ),
        migrations.AlterField(
            model_name='categoriarepuesto',
            name='descripcion',
            field=models.TextField(blank=True, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='tipo',
            field=models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida'), ('AJUSTE', 'Ajuste'), ('DEVOLUCION', 'Devolucion')], max_length=15, verbose_name='Tipo de movimiento'),
        ),
        migrations.AlterField(
            model_name='repuesto',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='repuestos', to='inventario.categoriarepuesto', verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='repuesto',
            name='codigo',
            field=models.CharField(help_text='Codigo unico del repuesto', max_length=50, unique=True, verbose_name='Codigo'),
        ),
        migrations.AlterField(
            model_name='repuesto',
            name='descripcion',
            field=models.TextField(blank=True, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='repuesto',
            name='stock_maximo',
            field=models.PositiveIntegerField(blank=True, help_text='Stock maximo recomendado', null=True, verbose_name='Stock maximo'),
        ),
        migrations.AlterField(
            model_name='repuesto',
            name='stock_minimo',
            field=models.PositiveIntegerField(default=5, help_text='Alerta cuando el stock baje de este valor', verbose_name='Stock minimo'),
        ),
        migrations.AlterField(
            model_name='repuesto',
            name='ubicacion',
            field=models.CharField(blank=True, help_text='Ej: Estante A-3, Caja 2', max_length=100, verbose_name='Ubicacion en bodega'),
        ),
    ]
