# Generated by Django 4.2.13 on 2026-05-18 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PROX_MANT', 'Próximo mantenimiento'), ('MANT_VENC', 'Mantenimiento vencido'), ('ORD_PEND', 'Orden pendiente'), ('VEH_LISTO', 'Vehículo listo para entrega'), ('RETRASO', 'Retraso en entrega'), ('RECORDATORIO', 'Recordatorio general')], max_length=15, verbose_name='Tipo de alerta')),
                ('nivel', models.CharField(choices=[('INFO', 'Información'), ('WARNING', 'Advertencia'), ('DANGER', 'Urgente')], default='INFO', max_length=10, verbose_name='Nivel')),
                ('mensaje', models.TextField(verbose_name='Mensaje')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Creada el')),
                ('fecha_vencimiento', models.DateTimeField(blank=True, null=True, verbose_name='Vence el')),
                ('leida', models.BooleanField(default=False, verbose_name='Leída')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
            ],
            options={
                'verbose_name': 'Alerta',
                'verbose_name_plural': 'Alertas',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
