# Generated by Django 4.2.13 on 2026-05-18 01:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehiculos', '0001_initial'),
        ('ordenes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('alertas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerta',
            name='destinatario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas_recibidas', to=settings.AUTH_USER_MODEL, verbose_name='Destinatario'),
        ),
        migrations.AddField(
            model_name='alerta',
            name='orden',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='ordenes.ordenservicio', verbose_name='Orden de servicio'),
        ),
        migrations.AddField(
            model_name='alerta',
            name='vehiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='vehiculos.vehiculo', verbose_name='Vehículo'),
        ),
        migrations.AddIndex(
            model_name='alerta',
            index=models.Index(fields=['leida', 'activa'], name='alertas_ale_leida_0161b6_idx'),
        ),
        migrations.AddIndex(
            model_name='alerta',
            index=models.Index(fields=['destinatario'], name='alertas_ale_destina_3a6c71_idx'),
        ),
        migrations.AddIndex(
            model_name='alerta',
            index=models.Index(fields=['tipo'], name='alertas_ale_tipo_04d22d_idx'),
        ),
    ]
