# Generated by Django 4.2.13 on 2026-06-28 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alertas', '0003_canales_plantillas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerta',
            name='canal',
            field=models.CharField(choices=[('INTERNA', 'Interna'), ('EMAIL', 'Correo electronico'), ('WHATSAPP', 'WhatsApp'), ('AMBOS', 'Correo y WhatsApp')], default='INTERNA', max_length=10, verbose_name='Canal de envio'),
        ),
        migrations.AlterField(
            model_name='alerta',
            name='leida',
            field=models.BooleanField(default=False, verbose_name='Leida'),
        ),
        migrations.AlterField(
            model_name='alerta',
            name='nivel',
            field=models.CharField(choices=[('INFO', 'Informacion'), ('WARNING', 'Advertencia'), ('DANGER', 'Urgente')], default='INFO', max_length=10, verbose_name='Nivel'),
        ),
    ]
