# Generated by Django 4.2.13 on 2026-06-28 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0002_remove_vehiculo_foto_restringir_tipos'),
        ('alertas', '0004_alter_alerta_canal_alter_alerta_leida_and_more'),
        ('ordenes', '0004_detalleordentrabajo_ordentrabajo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerta',
            name='orden',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='ordenes.ordentrabajo', verbose_name='Orden de trabajo'),
        ),
        migrations.AlterField(
            model_name='alerta',
            name='tipo',
            field=models.CharField(choices=[('PROX_MANT', 'Proximo mantenimiento'), ('MANT_VENC', 'Mantenimiento vencido'), ('ORD_PEND', 'Orden pendiente'), ('VEH_LISTO', 'Vehiculo listo para entrega'), ('RETRASO', 'Retraso en entrega'), ('RECORDATORIO', 'Recordatorio general')], max_length=15, verbose_name='Tipo de alerta'),
        ),
        migrations.AlterField(
            model_name='alerta',
            name='ultimo_error_envio',
            field=models.TextField(blank=True, verbose_name='Ultimo error de envio'),
        ),
        migrations.AlterField(
            model_name='alerta',
            name='vehiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='vehiculos.vehiculo', verbose_name='Vehiculo'),
        ),
        migrations.AlterField(
            model_name='plantillamensaje',
            name='canal',
            field=models.CharField(choices=[('EMAIL', 'Correo electronico'), ('WHATSAPP', 'WhatsApp')], max_length=10, verbose_name='Canal'),
        ),
    ]
