# Generated by Django 4.2.13 on 2026-06-28 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0002_remove_vehiculo_foto_restringir_tipos'),
        ('ordenes', '0006_detalleordentrabajo_servicio_and_more'),
        ('clientes', '0002_remove_cliente_telefono_alternativo'),
        ('alertas', '0005_alter_alerta_orden_alter_alerta_tipo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionRecordatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias_anticipacion', models.PositiveIntegerField(default=5, help_text='Cuántos días antes del mantenimiento enviar el recordatorio.', verbose_name='Días de anticipación')),
                ('activo', models.BooleanField(default=True, verbose_name='Sistema activo')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de recordatorio',
                'verbose_name_plural': 'Configuración de recordatorios',
            },
        ),
        migrations.AlterModelOptions(
            name='alerta',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Alerta interna', 'verbose_name_plural': 'Alertas internas'},
        ),
        migrations.AlterField(
            model_name='alerta',
            name='canal',
            field=models.CharField(choices=[('INTERNA', 'Interna'), ('EMAIL', 'Correo electrónico'), ('WHATSAPP', 'WhatsApp'), ('AMBOS', 'Correo y WhatsApp')], default='INTERNA', max_length=10, verbose_name='Canal de envío'),
        ),
        migrations.AlterField(
            model_name='alerta',
            name='leida',
            field=models.BooleanField(default=False, verbose_name='Leída'),
        ),
        migrations.AlterField(
            model_name='alerta',
            name='nivel',
            field=models.CharField(choices=[('INFO', 'Información'), ('WARNING', 'Advertencia'), ('DANGER', 'Urgente')], default='INFO', max_length=10, verbose_name='Nivel'),
        ),
        migrations.AlterField(
            model_name='alerta',
            name='tipo',
            field=models.CharField(choices=[('PROX_MANT', 'Próximo mantenimiento'), ('MANT_VENC', 'Mantenimiento vencido'), ('ORD_PEND', 'Orden pendiente'), ('VEH_LISTO', 'Vehículo listo para entrega'), ('RETRASO', 'Retraso en entrega'), ('RECORDATORIO', 'Recordatorio general')], max_length=15, verbose_name='Tipo de alerta'),
        ),
        migrations.AlterField(
            model_name='alerta',
            name='ultimo_error_envio',
            field=models.TextField(blank=True, verbose_name='Último error de envío'),
        ),
        migrations.AlterField(
            model_name='alerta',
            name='vehiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='vehiculos.vehiculo', verbose_name='Vehículo'),
        ),
        migrations.AlterField(
            model_name='plantillamensaje',
            name='canal',
            field=models.CharField(choices=[('EMAIL', 'Correo electrónico'), ('WHATSAPP', 'WhatsApp')], max_length=10, verbose_name='Canal'),
        ),
        migrations.CreateModel(
            name='RegistroMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_mantenimiento', models.CharField(default='Mantenimiento preventivo', max_length=120, verbose_name='Tipo de mantenimiento')),
                ('descripcion_trabajos', models.TextField(blank=True, verbose_name='Descripción de los trabajos realizados')),
                ('fecha_mantenimiento', models.DateField(verbose_name='Fecha del mantenimiento')),
                ('kilometraje_mantenimiento', models.PositiveIntegerField(default=0, verbose_name='Kilometraje al momento del mantenimiento (km)')),
                ('tipo_intervalo', models.CharField(choices=[('DIAS', 'Por tiempo (días)'), ('KM', 'Por kilometraje'), ('AMBOS', 'Por tiempo y kilometraje')], default='DIAS', max_length=5, verbose_name='Tipo de intervalo')),
                ('intervalo_dias', models.PositiveIntegerField(blank=True, help_text='Ej: 60 = cada 2 meses, 90 = cada 3 meses', null=True, verbose_name='Intervalo en días')),
                ('intervalo_km', models.PositiveIntegerField(blank=True, help_text='Ej: 5000, 10000', null=True, verbose_name='Intervalo en kilómetros')),
                ('fecha_proximo_mantenimiento', models.DateField(blank=True, null=True, verbose_name='Fecha del próximo mantenimiento')),
                ('kilometraje_proximo_mantenimiento', models.PositiveIntegerField(blank=True, null=True, verbose_name='Kilometraje del próximo mantenimiento (km)')),
                ('canal_envio', models.CharField(choices=[('EMAIL', 'Correo electrónico'), ('WHATSAPP', 'WhatsApp'), ('AMBOS', 'Correo y WhatsApp')], default='EMAIL', max_length=10, verbose_name='Canal de envío del recordatorio')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros_mantenimiento', to='clientes.cliente', verbose_name='Cliente')),
                ('orden', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registro_mantenimiento', to='ordenes.ordentrabajo', verbose_name='Orden de trabajo')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros_mantenimiento', to='vehiculos.vehiculo', verbose_name='Vehículo')),
            ],
            options={
                'verbose_name': 'Registro de mantenimiento',
                'verbose_name_plural': 'Registros de mantenimiento',
                'ordering': ['-fecha_mantenimiento'],
            },
        ),
        migrations.CreateModel(
            name='RecordatorioMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canal', models.CharField(choices=[('EMAIL', 'Correo electrónico'), ('WHATSAPP', 'WhatsApp'), ('AMBOS', 'Correo y WhatsApp')], max_length=10, verbose_name='Canal de envío')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de envío'), ('ENVIADO', 'Enviado correctamente'), ('ERROR', 'Error en el envío'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=10, verbose_name='Estado')),
                ('fecha_programada', models.DateField(help_text='Se calcula: fecha_proximo - días de anticipación', verbose_name='Fecha programada para envío')),
                ('fecha_envio', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y hora de envío real')),
                ('enviado_email', models.BooleanField(default=False, verbose_name='Email enviado')),
                ('enviado_whatsapp', models.BooleanField(default=False, verbose_name='WhatsApp enviado')),
                ('error_detalle', models.TextField(blank=True, verbose_name='Detalle del error')),
                ('intento_numero', models.PositiveIntegerField(default=1, verbose_name='N° de intento')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordatorios', to='alertas.registromantenimiento', verbose_name='Registro de mantenimiento')),
            ],
            options={
                'verbose_name': 'Recordatorio de mantenimiento',
                'verbose_name_plural': 'Recordatorios de mantenimiento',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.AddIndex(
            model_name='registromantenimiento',
            index=models.Index(fields=['vehiculo'], name='alertas_reg_vehicul_24f386_idx'),
        ),
        migrations.AddIndex(
            model_name='registromantenimiento',
            index=models.Index(fields=['cliente'], name='alertas_reg_cliente_6725ec_idx'),
        ),
        migrations.AddIndex(
            model_name='registromantenimiento',
            index=models.Index(fields=['fecha_proximo_mantenimiento'], name='alertas_reg_fecha_p_45cf90_idx'),
        ),
        migrations.AddIndex(
            model_name='registromantenimiento',
            index=models.Index(fields=['activo'], name='alertas_reg_activo_d28916_idx'),
        ),
        migrations.AddIndex(
            model_name='recordatoriomantenimiento',
            index=models.Index(fields=['estado'], name='alertas_rec_estado_224932_idx'),
        ),
        migrations.AddIndex(
            model_name='recordatoriomantenimiento',
            index=models.Index(fields=['fecha_programada'], name='alertas_rec_fecha_p_dddb34_idx'),
        ),
        migrations.AddIndex(
            model_name='recordatoriomantenimiento',
            index=models.Index(fields=['registro'], name='alertas_rec_registr_3df680_idx'),
        ),
    ]
