# Generated by Django 4.2.13 on 2026-06-28 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicio',
            options={'ordering': ['categoria', 'nombre'], 'verbose_name': 'Servicio', 'verbose_name_plural': 'Servicios'},
        ),
        migrations.AddField(
            model_name='servicio',
            name='categoria',
            field=models.CharField(choices=[('MANTENIMIENTO_PREVENTIVO', 'Mantenimiento Preventivo'), ('MECANICA_GENERAL', 'Mecanica General'), ('INYECCION', 'Inyeccion'), ('ELECTRICIDAD', 'Electricidad'), ('SUSPENSION', 'Suspension'), ('FRENOS', 'Frenos'), ('DIAGNOSTICO', 'Diagnostico'), ('COLISION', 'Colision'), ('PINTURA', 'Pintura')], default='MECANICA_GENERAL', max_length=30, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='descripcion',
            field=models.TextField(blank=True, verbose_name='Descripcion'),
        ),
        migrations.AddIndex(
            model_name='servicio',
            index=models.Index(fields=['categoria'], name='servicios_s_categor_6f425a_idx'),
        ),
    ]
