# Generated by Django 4.2.13 on 2026-07-06 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_movimientoinventario_orden_trabajo_and_more'),
        ('servicios', '0002_alter_servicio_options_servicio_categoria_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicioRepuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_sugerida', models.DecimalField(decimal_places=2, default=1, max_digits=8, verbose_name='Cantidad sugerida')),
                ('opcional', models.BooleanField(default=False, verbose_name='Es opcional')),
                ('nota', models.CharField(blank=True, max_length=200, verbose_name='Nota')),
                ('repuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios_sugeridos', to='inventario.repuesto', verbose_name='Repuesto')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repuestos_sugeridos', to='servicios.servicio', verbose_name='Servicio')),
            ],
            options={
                'verbose_name': 'Repuesto sugerido',
                'verbose_name_plural': 'Repuestos sugeridos',
                'ordering': ['servicio', 'opcional', 'repuesto__nombre'],
                'unique_together': {('servicio', 'repuesto')},
            },
        ),
    ]
