# Generated by Django 4.2.13 on 2026-05-18 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10, unique=True, verbose_name='Placa')),
                ('marca', models.CharField(max_length=60, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=80, verbose_name='Modelo')),
                ('anio', models.PositiveSmallIntegerField(verbose_name='Año')),
                ('color', models.CharField(blank=True, max_length=40, verbose_name='Color')),
                ('tipo_vehiculo', models.CharField(choices=[('AUTOMOVIL', 'Automóvil'), ('CAMIONETA', 'Camioneta'), ('SUV', 'SUV'), ('FURGONETA', 'Furgoneta'), ('CAMION', 'Camión'), ('OTRO', 'Otro')], default='AUTOMOVIL', max_length=15, verbose_name='Tipo de vehículo')),
                ('tipo_combustible', models.CharField(choices=[('GASOLINA', 'Gasolina'), ('DIESEL', 'Diésel'), ('HIBRIDO', 'Híbrido'), ('ELECTRICO', 'Eléctrico'), ('GAS', 'Gas')], default='GASOLINA', max_length=15, verbose_name='Tipo de combustible')),
                ('numero_vin', models.CharField(blank=True, help_text='Vehicle Identification Number (17 caracteres)', max_length=17, verbose_name='Número VIN')),
                ('numero_motor', models.CharField(blank=True, max_length=50, verbose_name='N° Motor')),
                ('kilometraje_actual', models.PositiveIntegerField(default=0, verbose_name='Kilometraje actual (km)')),
                ('cilindraje', models.CharField(blank=True, max_length=20, verbose_name='Cilindraje')),
                ('transmision', models.CharField(blank=True, choices=[('MANUAL', 'Manual'), ('AUTOMATICA', 'Automática'), ('CVT', 'CVT')], max_length=20, verbose_name='Transmisión')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='vehiculos/', verbose_name='Foto del vehículo')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehiculos', to='clientes.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
                'ordering': ['placa'],
                'indexes': [models.Index(fields=['placa'], name='vehiculos_v_placa_4999e1_idx'), models.Index(fields=['cliente'], name='vehiculos_v_cliente_88ee59_idx')],
            },
        ),
    ]
