# Generated by Django 4.2.13 on 2026-05-18 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(verbose_name='Descripción del servicio realizado')),
                ('km_al_servicio', models.PositiveIntegerField(default=0, verbose_name='Kilometraje al momento del servicio')),
                ('proximo_km_sugerido', models.PositiveIntegerField(blank=True, null=True, verbose_name='Próximo cambio sugerido (km)')),
                ('proxima_fecha_sugerida', models.DateField(blank=True, null=True, verbose_name='Próxima fecha sugerida')),
                ('costo', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Costo ($)')),
                ('fecha_servicio', models.DateField(verbose_name='Fecha del servicio')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Historial de mantenimiento',
                'verbose_name_plural': 'Historial de mantenimiento',
                'ordering': ['-fecha_servicio'],
            },
        ),
        migrations.CreateModel(
            name='TipoServicioMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('intervalo_km_recomendado', models.PositiveIntegerField(default=0, help_text='0 = no aplica por km', verbose_name='Intervalo recomendado (km)')),
                ('intervalo_dias_recomendado', models.PositiveIntegerField(default=0, help_text='0 = no aplica por tiempo', verbose_name='Intervalo recomendado (días)')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de mantenimiento',
                'verbose_name_plural': 'Tipos de mantenimiento',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ProgramaMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ultimo_km', models.PositiveIntegerField(default=0, verbose_name='Kilómetros en último servicio')),
                ('ultima_fecha', models.DateField(blank=True, null=True, verbose_name='Fecha del último servicio')),
                ('proximo_km', models.PositiveIntegerField(blank=True, null=True, verbose_name='Próximo servicio (km)')),
                ('proxima_fecha', models.DateField(blank=True, null=True, verbose_name='Próxima fecha de servicio')),
                ('intervalo_km', models.PositiveIntegerField(default=0, verbose_name='Intervalo personalizado (km)')),
                ('intervalo_dias', models.PositiveIntegerField(default=0, verbose_name='Intervalo personalizado (días)')),
                ('estado', models.CharField(choices=[('AL_DIA', 'Al día'), ('PROXIMO', 'Próximo (en los próximos 500 km / 15 días)'), ('VENCIDO', 'Vencido')], default='AL_DIA', max_length=10, verbose_name='Estado')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('tipo_servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='programas', to='mantenimiento.tiposerviciomantenimiento', verbose_name='Tipo de servicio')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programas_mantenimiento', to='vehiculos.vehiculo', verbose_name='Vehículo')),
            ],
            options={
                'verbose_name': 'Programa de mantenimiento',
                'verbose_name_plural': 'Programas de mantenimiento',
                'ordering': ['proxima_fecha', 'proximo_km'],
            },
        ),
    ]
