# Generated by Django 4.2.13 on 2026-05-18 01:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehiculos', '0001_initial'),
        ('mantenimiento', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historialmantenimiento',
            name='tecnico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial_realizado', to=settings.AUTH_USER_MODEL, verbose_name='Técnico'),
        ),
        migrations.AddField(
            model_name='historialmantenimiento',
            name='tipo_servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='historial', to='mantenimiento.tiposerviciomantenimiento', verbose_name='Tipo de servicio'),
        ),
        migrations.AddField(
            model_name='historialmantenimiento',
            name='vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_mantenimiento', to='vehiculos.vehiculo', verbose_name='Vehículo'),
        ),
        migrations.AlterUniqueTogether(
            name='programamantenimiento',
            unique_together={('vehiculo', 'tipo_servicio')},
        ),
        migrations.AddIndex(
            model_name='historialmantenimiento',
            index=models.Index(fields=['vehiculo'], name='mantenimien_vehicul_4586e8_idx'),
        ),
        migrations.AddIndex(
            model_name='historialmantenimiento',
            index=models.Index(fields=['fecha_servicio'], name='mantenimien_fecha_s_b911d3_idx'),
        ),
    ]
