# Generated by Django 4.2.13 on 2026-06-28 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialmantenimiento',
            name='descripcion',
            field=models.TextField(verbose_name='Descripcion del servicio realizado'),
        ),
    ]
