# Generated by Django 4.2.13 on 2026-06-28 18:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vehiculos', '0002_remove_vehiculo_foto_restringir_tipos'),
        ('ordenes', '0004_detalleordentrabajo_ordentrabajo_and_more'),
        ('mantenimiento', '0004_alter_historialmantenimiento_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialmantenimiento',
            name='orden',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial_mantenimiento', to='ordenes.ordentrabajo', verbose_name='Orden de trabajo'),
        ),
        migrations.AlterField(
            model_name='historialmantenimiento',
            name='proxima_fecha_sugerida',
            field=models.DateField(blank=True, null=True, verbose_name='Proxima fecha sugerida'),
        ),
        migrations.AlterField(
            model_name='historialmantenimiento',
            name='proximo_km_sugerido',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Proximo cambio sugerido (km)'),
        ),
        migrations.AlterField(
            model_name='historialmantenimiento',
            name='tecnico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial_realizado', to=settings.AUTH_USER_MODEL, verbose_name='Tecnico'),
        ),
        migrations.AlterField(
            model_name='historialmantenimiento',
            name='vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_mantenimiento', to='vehiculos.vehiculo', verbose_name='Vehiculo'),
        ),
        migrations.AlterField(
            model_name='programamantenimiento',
            name='estado',
            field=models.CharField(choices=[('AL_DIA', 'Al dia'), ('PROXIMO', 'Proximo (en los proximos 500 km / 15 dias)'), ('VENCIDO', 'Vencido')], default='AL_DIA', max_length=10, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='programamantenimiento',
            name='intervalo_dias',
            field=models.PositiveIntegerField(default=0, verbose_name='Intervalo personalizado (dias)'),
        ),
        migrations.AlterField(
            model_name='programamantenimiento',
            name='proxima_fecha',
            field=models.DateField(blank=True, null=True, verbose_name='Proxima fecha de servicio'),
        ),
        migrations.AlterField(
            model_name='programamantenimiento',
            name='proximo_km',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Proximo servicio (km)'),
        ),
        migrations.AlterField(
            model_name='programamantenimiento',
            name='ultima_fecha',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha del ultimo servicio'),
        ),
        migrations.AlterField(
            model_name='programamantenimiento',
            name='ultimo_km',
            field=models.PositiveIntegerField(default=0, verbose_name='Kilometros en ultimo servicio'),
        ),
        migrations.AlterField(
            model_name='programamantenimiento',
            name='vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programas_mantenimiento', to='vehiculos.vehiculo', verbose_name='Vehiculo'),
        ),
        migrations.AlterField(
            model_name='tiposerviciomantenimiento',
            name='descripcion',
            field=models.TextField(blank=True, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='tiposerviciomantenimiento',
            name='intervalo_dias_recomendado',
            field=models.PositiveIntegerField(default=0, help_text='0 = no aplica por tiempo', verbose_name='Intervalo recomendado (dias)'),
        ),
    ]
